### PR TITLE
User stderr

### PR DESCRIPTION
**Pull request by konsumer**
Use stderr for presidential non-endorsement.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Oops, sorry, didn't see this and rolled with this directly while I fixed up tests.

**Comment by rgbkrk** [comment]
Thanks for coming back to add this by the way. :tada:

**Comment by rgbkrk** [comment]
Went ahead and added you to the project @konsumer. Thanks for the PRs.

**Comment by konsumer** [comment]
Thanks!

**Pull request closed without merging**
