### PR TITLE
added ansi seal and non-endorsement message

### LINKED ISSUE #1: Request: Presidential Seal of Approval
Can we get an actual presidential seal of approval badge?

https://backpacksandbabygrows.files.wordpress.com/2014/08/approved.png
http://www.theuspresidents.org/wp-content/uploads/2015/04/Presidential_Seal_TheUSPresidents.jpg

### PR DESCRIPTION
**Pull request by konsumer**
If there are errors, you see "The president cannot endorse this code." and if there isn't, you see an ANSI seal of the president. Resolves #1.

### CODE REVIEW

**Comment by konsumer** [comment]
screen shot 2015-11-17 at 12 56 56 pm

**Comment by rgbkrk** [comment]
omg

**Comment by rgbkrk** [comment]
Should this be written out to stderr in case any tools use the output from stdout?

**Comment by konsumer** [comment]
Good call.

**Comment by rgbkrk** [comment]
ok, didn't expect that to show a merge.

**Comment by rgbkrk** [comment]
```
$ git push -u origin seal
Counting objects: 12, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (12/12), 4.22 KiB | 0 bytes/s, done.
Total 12 (delta 5), reused 0 (delta 0)
To git@github.com:rgbkrk/obama.git
   3024a75..d246b4b  seal -> master
Branch seal set up to track remote branch master from origin.
```

**Comment by rgbkrk** [comment]
Meant to submit a PR to your PR there to bring some deps up to date for the sake of the tests.

**Comment by rgbkrk** [comment]
Addressed those bits directly, thanks @konsumer! This also ended up bringing our dependencies up to date.

`v0.2.0` is out!

**Comment by rgbkrk** [comment]
screenshot 2015-11-17 17 08 28

**Comment by konsumer** [comment]
:)

**Pull request merged**
