### PR TITLE
Obama will soon not be president

### PR DESCRIPTION
**Pull request by konsumer**
Sadly, he will soon not be president. This updates the presidential non-endorsement message.

### CODE REVIEW

**Comment by konsumer** [comment]
If only inauguration worked this way:
screen shot 2017-01-17 at 3 20 11 pm

**Comment by rgbkrk** [comment]
I now have a case of the sads.

**Comment by rgbkrk** [comment]
:shipit:

**Comment by rgbkrk** [comment]
He's still Mr. President to me.

**Comment by konsumer** [comment]
Me too.

**Pull request merged**
